### ISSUE TITLE
API base url is envirnoment sepcific

### ISSUE THREAD

**Issue by pestig** [GergelyKarl/angular-practice#3]
https://github.com/GergelyKarl/angular-practice/blob/8eacc3ca414f9a609efcfb28ebce9c30efc42a0d/src/app/core/get-api.service.ts#L11

API base url should be in environments settings:

https://github.com/GergelyKarl/angular-practice/blob/main/src/environments/environment.ts

**Comment by GergelyKarl** [comment]
done
